### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by 2803media** [mapbox/mapbox-geostats#43]
Hi I try to install the npm package but it failed... See the result below:

```
macbook-hela-2:67 henri$ npm install -g @mapbox/mapbox-geostats
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated protozero@1.5.1: protozero should no longer be used via npm, install instead via https://github.com/mapbox/mason
/usr/local/bin/mapbox-geostats -> /usr/local/lib/node_modules/@mapbox/mapbox-geostats/bin/mapbox-geostats
/usr/local/bin/mapbox-geostats-validate -> /usr/local/lib/node_modules/@mapbox/mapbox-geostats/bin/mapbox-geostats-validate

> sqlite3@4.0.6 install /usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
[sqlite3] Success: "/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/sqlite3/lib/binding/node-v64-darwin-x64/node_sqlite3.node" is installed via remote

> mapnik@3.7.2 install /usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.14.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v64-darwin-x64-Release.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@10.14.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
/bin/sh: mapnik-config: command not found
gyp: Call to 'mapnik-config --cflags' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding"
gyp ERR! cwd /usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik
node-pre-gyp ERR! node -v v10.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding' (1)
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik/lib/binding"
gyp ERR! cwd /usr/local/lib/node_modules/@mapbox/mapbox-geostats/node_modules/mapnik
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/henri/.npm/_logs/2019-03-04T12_54_05_532Z-debug.log
```

**Comment by mapsam** [comment]
Hi @2803media - it looks like mapnik 3.7.2 doesn't have prebuilt binaries for node v10. We should update this library to use mapnik 4.x, which has node v10 binaries. In the meantime, downgrading to node 8 should get you moving.

**Comment by mhines-usgs** [comment]
I am also having issues installing this and am not super familiar with the errors I'm seeing - any suggestions? I believe I have node v8:

```
megan@megan-VirtualBox:~/Documents/mapbox-geostats$ sudo npm install @mapbox/mapbox-geostats --production

> mapnik@3.7.2 install /home/megan/Documents/mapbox-geostats/node_modules/mapnik
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/mapnik/v3.7.2/node-v57-linux-x64-Release.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for mapnik@3.7.2 and node@8.16.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/megan/Documents/mapbox-geostats/node_modules/mapnik/build'
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node" "--module_name=mapnik" "--module_path=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding"
gyp ERR! cwd /home/megan/Documents/mapbox-geostats/node_modules/mapnik
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/megan/Documents/mapbox-geostats/node_modules/mapnik/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-54-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/megan/Documents/mapbox-geostats/node_modules/mapnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/megan/Documents/mapbox-geostats/node_modules/mapnik
node-pre-gyp ERR! node -v v8.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding/mapnik.node --module_name=mapnik --module_path=/home/megan/Documents/mapbox-geostats/node_modules/mapnik/lib/binding' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mapnik@3.7.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mapnik@3.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/megan/.npm/_logs/2019-07-08T21_06_39_216Z-debug.log
megan@megan-VirtualBox:~/Documents/mapbox-geostats$ 
```
